# Orientation (quaternion)
float64 orientation_x
float64 orientation_y
float64 orientation_z
float64 orientation_w
#float64[9] orientation_covariance

# Angular velocity
float64 angular_velocity_x
float64 angular_velocity_y
float64 angular_velocity_z
#float64[9] angular_velocity_covariance

# Linear acceleration
float64 linear_acceleration_x
float64 linear_acceleration_y
float64 linear_acceleration_z
#float64[9] linear_acceleration_covariance